export const dummyConversationData = [
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: true,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: true,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: true,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
];
