export const dummyConversationData = [
  {
    id: 1,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 2,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: true,
  },
  {
    id: 3,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 4,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 5,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: true,
  },
  {
    id: 6,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 7,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 8,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: true,
  },
  {
    id: 9,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 10,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 11,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 11,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 11,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 11,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 11,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 11,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
  {
    id: 11,
    profileUrl: "/assets/profile.png",
    name: "Wajid Ullah",
    lastMsg: "Ok Sure...",
    time: "12",
    messageSeen: false,
  },
];
